trigger:
  batch: true
  branches:
    include:
      - master
      - Releases/*
    exclude:
      - refs/tags/no-build
  tags:
    exclude:
      - "*"

pool:
  name: "CK-11-MainBuildPool"
  demands:
    - npm

resources:
  repositories:
    - repository: build-scripts
      type: git
      name: Development/Build.Scripts
      ref: refs/heads/release/v2

variables:
  - template: scripts/default-variables.yml@build-scripts
  - group: Build.Common
  - group: Build.Master

steps:
  - checkout: self
  - checkout: build-scripts

  - script: npm install
    displayName: Install
    workingDirectory: $(Build.Repository.Name)

  - script: npm run build
    displayName: Restore designsystem projects
    workingDirectory: $(Build.Repository.Name)

  - template: scripts/add-to-archive.yml@build-scripts
    parameters:
      archiveFile: $(Build.ArtifactStagingDirectory)/publish/addons/designsystem/web/designsystem.zip
      sourceFolder: $(Build.Repository.Name)/dist
      sourceRootName: designsystem

  - template: scripts/publish-artifact.yml@build-scripts
    parameters:
      sourceArtifactFolder: $(Build.ArtifactStagingDirectory)/publish

  - template: scripts/publish-build-to-ck-build.yml@build-scripts

  - script: rm -rfv *
    workingDirectory: $(Build.ArtifactStagingDirectory)
    displayName: "Очистка после сбоки шаг 1"

  - script: rm -rfv *
    workingDirectory: $(Build.Repository.Name)
    displayName: "Очистка после сбоки шаг 2"
