trigger:
  batch: true
  branches:
    include:
      - Releases/11.7.1
    exclude:
      - refs/tags/no-build
  tags:
    exclude:
      - "*"

    pool:
      name: "CK-11-MainBuildPool"
      demands:
        - npm

    variables:
      - template: scripts/default-variables.yml@build-scripts

    steps:
      - checkout: self
      - checkout: build-scripts

      - script: npm install
        displayName: Install
        workingDirectory: $(Build.Repository.Name)/src

      - script: npm run build
        displayName: Restore dsyst projects
        workingDirectory: $(Build.Repository.Name)/src

      - template: scripts/add-to-archive.yml@build-scripts
        parameters:
          archiveFile: $(Build.ArtifactStagingDirectory)/publish/addons/dsyst/web/dsyst.zip
          sourceFolder: $(Build.Repository.Name)/src/dsyst/dist/dsyst
          sourceRootName: dsyst

      - template: scripts/publish-artifact.yml@build-scripts
        parameters:
          sourceArtifactFolder: $(Build.ArtifactStagingDirectory)/publish

      - template: scripts/publish-build-to-ck-build.yml@build-scripts

      - script: rm -rfv *
        workingDirectory: $(Build.ArtifactStagingDirectory)
        displayName: "Очистка после сбоки шаг 1"

      - script: rm -rfv *
        workingDirectory: $(Build.Repository.Name)
        displayName: "Очистка после сбоки шаг 2"
