trigger:
  batch: true
  branches:
    include:
      - add-story-v24
  tags:
    exclude:
      - '*'

pool:
  name: 'tfs-ext-pool-1'
  demands:
    - npm

steps:
  - checkout: self

  - task: Bash@3
    displayName: Install
    inputs:
      targetType: 'inline'
      script: |
        npm config set https-proxy http://proxy-ext.sandbox.local:8080
        npm install
      workingDirectory: $(Build.SourcesDirectory)

  - task: Bash@3
    displayName: Restore dx-custom-themes projects
    inputs:
      targetType: 'inline'
      script: |
        npm run build-storybook
      workingDirectory: $(Build.SourcesDirectory)

  - task: CopyFilesOverSSH@0
    displayName: Copy ../dist/storybook/dx-monitel-components to /var/www/html/24
    inputs:
      sshEndpoint: ssh_web-storybook.sandbox.local
      sourceFolder: "$(Build.SourcesDirectory)/dist/storybook/dx-monitel-components"
      contents: '**'
      targetFolder: "/var/www/html/24"
      cleanTargetFolder: true
      cleanHiddenFilesInTarget: true
      readyTimeout: '20000'
      #flattenFolders: false # boolean. Flatten folders. Default: false.
