import { Meta, StoryObj, moduleMetadata } from '@storybook/angular';
import { DxDataGridModule } from 'devextreme-angular';
import { MeDataGridDirective } from '../../public-api';

const columnsData = ['CompanyName', 'Phone', 'Fax', 'City', 'State'];

export default {
  title: 'Components/DataGrid(RC)',
  decorators: [
    moduleMetadata({
      declarations: [MeDataGridDirective],
      imports: [DxDataGridModule],
    }),
  ],

  argTypes: {
    dataSource: {
      control: 'text',
    },
    size: {
      control: 'select',
      options: ['small', 'medium', 'large'],
      description: 'Размер компонента',
    },
    height: {
      control: 'text',
      description: 'Занимаемая компонентом высота',
    },
    hint: {
      control: 'text',
      description:
        'Задает текст для подсказки, которая появляется, когда пользователь приостанавливает работу с компонентом пользовательского интерфейса',
    },
    showBorders: {
      control: 'boolean',
      description: 'Показывать ли границы ячейки',
    },
    showPageSizeSelector: {
      control: 'boolean',
      description: 'Показывать ли компонент выбора размера страницы',
    },
    displayMode: {
      control: 'select',
      options: ['compact', 'full'],
      description: 'Режим отображения PageSizeSelector',
    },
    allowedPageSizes: {
      control: 'text',
      description: 'Разрешенные размеры страницы',
    },
    showInfo: {
      control: 'boolean',
      description: 'Показывать ли компонент информации о странице',
    },
    infoText: {
      control: 'text',
      description: 'Текст информации о странице',
    },
    showNavigationButtons: {
      control: 'boolean',
      description: 'Показывать кнопки навигации',
    },
  },

  args: {
    dataSource: [
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
    ],
    size: 'small',
    showBorders: true,
    hint: 'Hint text',
    showPageSizeSelector: true,
    allowedPageSizes: 1,
    displayMode: 'full',
    showInfo: true,
    infoText: 'Записей: {2}',
    showNavigationButtons: true,
  },
  render: (args) => ({
    props: args,
    template: `
			<dx-data-grid
				meDataGrid
				id="gridContainer"
				[dataSource]="dataSource"
				[size]="size"
				[keyExpr]="'ID'"
				[allowColumnReordering]="true"
				[height]="height"
				[showBorders]="showBorders"
				[hint]="hint"
			>
				<dxi-column *ngFor="let column of columns" [dataField]="column"></dxi-column>
				<dxo-search-panel [visible]="true"></dxo-search-panel>
				<dxo-paging [pageSize]="10"></dxo-paging>
				<dxo-pager
					[showPageSizeSelector]="showPageSizeSelector"
					[(allowedPageSizes)]="allowedPageSizes"
					[displayMode]="displayMode"
					[showInfo]="showInfo"
					[infoText]="infoText"
					[showNavigationButtons]="showNavigationButtons"
					></dxo-pager>
				<dxo-group-panel [visible]="true"></dxo-group-panel>
			</dx-data-grid>
		`,
  }),
} as Meta;

export const DataGrid: StoryObj = {};
