export const dataGridMockSourceData = [
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 1',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 2',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 3',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
  {
    ID: 1,
    CompanyName: 'Company Name 4',
    Phone: 'Phone 1',
    Fax: 'Fax 1',
    City: 'City 1',
    State: 'State 1',
  },
  {
    ID: 2,
    CompanyName: 'Company Name 5',
    Phone: 'Phone 2',
    Fax: 'Fax 2',
    City: 'City 2',
    State: 'State 2',
  },
  {
    ID: 3,
    CompanyName: 'Company Name 6',
    Phone: 'Phone 3',
    Fax: 'Fax 3',
    City: 'City 3',
    State: 'State 3',
  },
];
