import { Meta, StoryObj, moduleMetadata } from '@storybook/angular';
import { DxDataGridModule } from 'devextreme-angular';
import { MeBadgeComponent, MeDataGridDirective } from '../../public-api';

export default {
  title: 'Components/DataGrid(RC)',
  component: MeBadgeComponent,
  decorators: [
    moduleMetadata({
      declarations: [MeDataGridDirective],
      imports: [DxDataGridModule],
    }),
  ],

  argTypes: {
    dataSource: {
      control: 'text',
    },
    size: {
      control: 'select',
      options: ['small', 'medium', 'large'],
      description: 'Размер компонента',
    },
    showPageSizeSelector: {
      control: 'select',
      options: [true, false],
      description:
        'Относится к Pagination. Показывать ли выбор колличества строк на странице. Тэг `dxo-pager`',
    },
    displayMode: {
      control: 'select',
      options: ['compact', 'full'],
      description: 'Относится к Pagination. Режим отображения PageSizeSelector',
    },
    pageSize: {
      control: 'text',
      description:
        'Относится к Pagination. Разрешенные размеры страницы. Тэг `dxo-paging`',
    },
    showInfo: {
      control: 'select',
      options: [true, false],
      description:
        'Относится к Pagination. Показывать ли компонент информации о странице. Тэг `dxo-pager`',
    },
    infoText: {
      control: 'text',
      description:
        'Относится к Pagination. Текст информации о странице. Тэг `dxo-pager`',
    },
    showNavigationButtons: {
      control: 'select',
      options: [true, false],
      description:
        'Относится к Pagination. Показывать кнопки навигации. Тэг `dxo-pager`',
    },
  },

  args: {
    dataSource: [
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 1',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 2',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 3',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
      {
        ID: 1,
        CompanyName: 'Company Name 4',
        Phone: 'Phone 1',
        Fax: 'Fax 1',
        City: 'City 1',
        State: 'State 1',
      },
      {
        ID: 2,
        CompanyName: 'Company Name 5',
        Phone: 'Phone 2',
        Fax: 'Fax 2',
        City: 'City 2',
        State: 'State 2',
      },
      {
        ID: 3,
        CompanyName: 'Company Name 6',
        Phone: 'Phone 3',
        Fax: 'Fax 3',
        City: 'City 3',
        State: 'State 3',
      },
    ],
    size: 'medium',
    showPageSizeSelector: true,
    displayMode: 'full',
    showInfo: true,
    infoText: 'Записей: {2}',
    showNavigationButtons: true,
    pageSize: '10',
  },
  render: (args) => ({
    props: args,
    template: `
			<dx-data-grid
				meDataGrid
				id="gridContainer"
				[(dataSource)]="dataSource"
				[size]="size"
				[allowColumnReordering]="true"
			>
				<dxo-search-panel [visible]="true"></dxo-search-panel>
				<dxo-paging [(pageSize)]="pageSize" [showPageSizeSelector]></dxo-paging>
				<dxo-pager
					[showPageSizeSelector]="showPageSizeSelector"
					[displayMode]="displayMode"
					[showInfo]="showInfo"
					[infoText]="infoText"
					[showNavigationButtons]="showNavigationButtons"
					></dxo-pager>
				<dxo-group-panel [visible]="true"></dxo-group-panel>
			</dx-data-grid>`,
  }),
} as Meta;

export const DataGrid: StoryObj = {};

export const WithCounter: StoryObj = {
  render: (args) => ({
    props: args,
    template: `<dx-data-grid
  meDataGrid
  [dataSource]="dataSource"
>
  <dxo-paging [(pageSize)]="pageSize" [showPageSizeSelector]></dxo-paging>
  <dxi-column dataField="CompanyName"></dxi-column>
  <dxi-column dataField="Fax"></dxi-column>
  <dxi-column dataField="Phone"></dxi-column>
  <dxi-column
  dataField="ID"
  cellTemplate="cellTemplate"></dxi-column>
  <div *dxTemplate="let cell of 'cellTemplate'">
    <me-badge [value]="[cell.data.ID]"></me-badge>
  </div>
</dx-data-grid>`,
  }),
};
